spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://toy.chgmoegews30.eu-north-1.rds.amazonaws.com:3306/toy?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    import: secret.yml

springdoc:
  packages-to-scan: likelion.practice.controller # 컨트롤러 가져오기
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /api-docs
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: method

